//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE
    {
        public DEVICE()
        {
            this.LISTA_CONTATOS = new HashSet<LISTA_CONTATOS>();
        }
    
        public string uuid { get; set; }
        public Nullable<System.DateTime> dateRegistro { get; set; }
        public string nmModel { get; set; }
    
        public virtual ICollection<LISTA_CONTATOS> LISTA_CONTATOS { get; set; }
    }
}
