//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_CONTATOS
    {
        public int idLISTA_CONTATOS { get; set; }
        public string uuid { get; set; }
        public string contact_list { get; set; }
        public string hashcode { get; set; }
    
        public virtual DEVICE DEVICE { get; set; }
    }
}
